Calendar/urls.py
from django.conf.urls import patterns, url

from Calendar import views

urlpatterns = patterns('',
    url(r'^$', views.index),
    url(r'^create/', views.create),
    url(r'^makeView/', views.makeView),
    url(r'^edit/(\w+)', views.editRequest),
    url(r'^viewrequest/(\w+)', views.viewRequest),
    url(r'^save/', views.create),
    url(r'^delete/(\w+)', views.deleteRequest),
    url(r'^assign/(\w+)', views.assign),
    url(r'^accounts/login/', 'django.contrib.auth.views.login'),
    url(r'^login/', views.login),
    url(r'^logout/', views.logout_view),
)

Environnements/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('Calendar.urls')),
    # Examples:
    # url(r'^$', 'Environnements.views.home', name='home'),
    # url(r'^Environnements/', include('Environnements.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

Calendar/models.py
#-*- coding: utf-8 -*-
from django.db import models
from datetime import date
import datetime


class Application(models.Model):
	appname = models.CharField(max_length=30, unique=True)

	def __unicode__(self):
		return self.appname

        def get_appname(self):
                return self.appname

	class Meta:
        	ordering = ('appname',)
		
#Each Envs instance will contain all available applications in the related env
class Envs(models.Model):
    	name = models.CharField(max_length=10, unique=True)
	applications = models.ManyToManyField(Application)

	def __unicode__(self):
		return self.name

	class Meta:
		ordering = ('name',)

VER_CHOICES = (
        ('Prod', 'prod'),
        ('Release', 'release'),
)

class Request(models.Model):
	#Version des programmes et de la copie de la db
	Prod = 'Prod'
	Release = 'Release'
	VER_CHOICES = (
	        (Prod, 'Prod'),
        	(Release, 'Release'),
	)

	#types de batche a tourner
	NoBatchs = 'Aucun'
	Daily = 'Journalier'
	OnDemand = 'A la demande'
	BATCH_CHOICES = (
		(NoBatchs, 'Aucun'),
		(Daily, 'Journalier'),
		(OnDemand, 'A la demande'),
	)	

	date_creation = models.DateTimeField(auto_now_add=True)
	title = models.CharField(max_length=200)
	reference = models.CharField(max_length=50)
	trigram = models.CharField(max_length=3)
	start = models.DateField()
	end = models.DateField()
	version = models.CharField(max_length=10, choices=VER_CHOICES, default=Prod)
	refresh = models.BooleanField()
	daterefresh = models.DateField(null=True, blank=True)
	batchs = models.BooleanField()
	batchType = models.CharField(max_length=15, choices=BATCH_CHOICES, default=NoBatchs)
	apps = models.ManyToManyField('Application')
	env = models.ForeignKey(Envs, null=True,blank=True)
	comments = models.TextField()

	def __unicode__(self):
		return self.title

	def get_apps(self):
		return ", ".join([p.appname for p in self.apps.all()])

	def retStart(self):
		return datetime.datetime.strptime(self.start, "%m/%d/%Y").date()

	def retEnd(self):
		return datetime.datetime.strptime(self.end, "%m/%d/%Y").date()

	class Meta:
		ordering = ('-date_creation',)

class History(models.Model):
	request = models.ForeignKey('Request')
	datemodif = models.DateTimeField(auto_now_add=True, auto_now=True)
	fieldmodified = models.CharField(max_length=50)
	valuebefore = models.TextField(null=True, blank=True)
	valueafter = models.TextField(null=True, blank=True)

	class Meta:
		ordering = ('-datemodif',)

Calendar/views.py
#-*- coding: utf-8 -*- 
from django.shortcuts import render, render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django import forms
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.core.mail import send_mail
import time
from datetime import date
from datetime import datetime
import datetime
import collections
import re
from Calendar.models import Envs, Application, Request, History

Informed_group='toto@com.fr'

class RequestFormAssign(forms.ModelForm):
        #Conserver la propriete required = false de daterefresh
        def __init__(self, *args, **kwargs):
                super(RequestFormAssign, self).__init__(*args, **kwargs)
                self.fields['daterefresh'].required = False
                self.fields['comments'].required = False

        start = forms.DateField(('%m/%d/%Y',), label='Debut', widget=forms.DateTimeInput(format='%m/%d/%Y', attrs={'id':'dateFrom'}))
        end = forms.DateField(('%m/%d/%Y',), label='Fin', widget=forms.DateTimeInput(format='%m/%d/%Y', attrs={'id':'dateTo'}))
        daterefresh = forms.DateField(('%m/%d/%Y',), label='Date du refresh', widget=forms.DateTimeInput(format='%m/%d/%Y', attrs={'id':'dateRefresh'}))

	def clean_end(self):
                cleaned_data = self.cleaned_data
                start = cleaned_data.get('start')
                end = cleaned_data.get('end')
                if end < start:
                        raise forms.ValidationError("La date de debut doit etre inferieure a la date de fin")
                return cleaned_data['end']

        def clean_daterefresh(self):
                cleaned_data = self.cleaned_data
                if cleaned_data.get('refresh') == True:
                        if not cleaned_data.get('daterefresh'):
                                raise forms.ValidationError("Veuillez preciser la date du refresh souhaite")
           	return cleaned_data['daterefresh']



        class Meta:
                model = Request


class RequestForm(forms.ModelForm):
	#Conserver la propriete required = false de daterefresh
	def __init__(self, *args, **kwargs):
		super(RequestForm, self).__init__(*args, **kwargs)
		self.fields['daterefresh'].required = False
		self.fields['comments'].required = False

	title = forms.CharField(label='Objet de la demande', widget=forms.TextInput(attrs={'id': 'reqtitle'}))
        trigram = forms.CharField(label='Trigramme', widget=forms.TextInput())
        refresh = forms.BooleanField(label='Besoin de refresh')
        apps = forms.CharField(label='Applications', widget=forms.TextInput())

	start = forms.DateField(('%m/%d/%Y',), label='Debut', widget=forms.DateTimeInput(format='%m/%d/%Y', attrs={'id':'dateFrom'}))
	end = forms.DateField(('%m/%d/%Y',), label='Fin', widget=forms.DateTimeInput(format='%m/%d/%Y', attrs={'id':'dateTo'}))
	daterefresh = forms.DateField(('%m/%d/%Y',), label='Date du refresh', widget=forms.DateTimeInput(format='%m/%d/%Y', attrs={'id':'dateRefresh'}))

	def clean_start(self):
		cleaned_data = self.cleaned_data
                start = cleaned_data.get('start')
		if start < datetime.datetime.now().date():
			raise forms.ValidationError("La date de debut doit etre superieure a la date courante")	
		return cleaned_data['start']

	def clean_end(self):
		cleaned_data = self.cleaned_data
		end = cleaned_data.get('end')
		start = cleaned_data.get('start')
		if end and start:
			if end < start:
				raise forms.ValidationError("La date de debut doit etre inferieure a la date de fin")	
		return cleaned_data['end']
	

	def clean_daterefresh(self):
		cleaned_data = self.cleaned_data
		if cleaned_data.get('refresh') == True:
			if not cleaned_data.get('daterefresh'):
				raise forms.ValidationError("Veuillez preciser la date du refresh souhaite")
		return cleaned_data['daterefresh']

		
	class Meta:
		model = Request
		exclude = ['env']


class RequestFormEdit(forms.ModelForm):
        #Conserver la propriete required = false de daterefresh
        def __init__(self, *args, **kwargs):
                super(RequestFormEdit, self).__init__(*args, **kwargs)
                self.fields['daterefresh'].required = False
                self.fields['comments'].required = False

	#Version des programmes et de la copie de la db
        Prod = 'Prod'
        Release = 'Release'
        VER_CHOICES = (
                (Prod, 'Prod'),
                (Release, 'Release'),
        )

        #types de batche a tourner
        NoBatchs = 'Aucun'
        Daily = 'Journalier'
        OnDemand = 'A la demande'
        BATCH_CHOICES = (
                (NoBatchs, 'Aucun'),
                (Daily, 'Journalier'),
                (OnDemand, 'A la demande'),
        )



        title = forms.CharField(label='Objet de la demande', widget=forms.TextInput(attrs={'id': 'reqtitle'}))
        trigram = forms.CharField(label='Trigramme', widget=forms.TextInput())
        comments = forms.CharField(label='Commentaires', widget=forms.Textarea())
	batchType = forms.ChoiceField(label='Type de batchs', choices=BATCH_CHOICES)
	version = forms.ChoiceField(label='Version des programmes et db', choices=VER_CHOICES)

        start = forms.DateField(('%m/%d/%Y',), label='Debut', widget=forms.DateTimeInput(format='%m/%d/%Y', attrs={'id':'dateFrom'}))
        end = forms.DateField(('%m/%d/%Y',), label='Fin', widget=forms.DateTimeInput(format='%m/%d/%Y', attrs={'id':'dateTo'}))
        daterefresh = forms.DateField(('%m/%d/%Y',), label='Date du refresh', widget=forms.DateTimeInput(format='%m/%d/%Y', attrs={'id':'dateRefresh'}))

        def clean_end(self):
                cleaned_data = self.cleaned_data
                end = cleaned_data.get('end')
                start = cleaned_data.get('start')
                if end and start:
                        if end < start:
                                raise forms.ValidationError("La date de debut doit etre inferieure a la date de fin")
                return cleaned_data['end']


        def clean_daterefresh(self):
                cleaned_data = self.cleaned_data
                if cleaned_data.get('refresh') == True:
                        if not cleaned_data.get('daterefresh'):
                                raise forms.ValidationError("Veuillez preciser la date du refresh souhaite")
                return cleaned_data['daterefresh']

	def clean_batchType(self):
		cleaned_data = self.cleaned_data
		if cleaned_data.get('batchs') == False:
			cleaned_data['batchType'] = 'Aucun'
		return cleaned_data['batchType']


        class Meta:
                model = Request
                exclude = ['env']



def create(request):
	"""
	La fonction create recupere les donnees du formulaire, cree une instance de Request et la sauve dans la db.
	A l'ouverture de la page, le formulaire vide est cree par le passage dans le else: form = RequestForm()
	Lorsque le formulaire est rempli et le bouton Sauvegarder presse, l'instance de Request est cree puis sauvegardee dans la db si le formulaire est valide.
	"""
	if request.method == 'POST':
		form = RequestForm(request.POST)
		if form.is_valid():
			form.save()
			req = Request.objects.get(title=request.POST['title'])
			applist = req.get_apps()
			message = "Bonjour, vous avez envoye une demande d'environnement de test pour le sujet " + request.POST['title'] + ".\nVotre demande est la suivante :\n\tReference : " + request.POST['reference'] + "i\n\t Date de debut : " +request.POST['start'] + "\n\tDate de fin : " +request.POST['end']+ "\n\tVersion des programmes et DB : " + request.POST['version'] + "\n\tDate des donnees souhaitee : " +request.POST['daterefresh'] + "\n\tTypes de batchs : " +request.POST['batchType'] + "\n\tApplications necessaires : " + applist + "\n\nCette requete sera prise en compte par l'equipe Environnement Management dans les plus brefs delais."
			send_mail("Demande d'environnement de test pour "+request.POST['title'], message, Informed_group, [request.POST['trigram']+'@ubp.ch'], fail_silently=False)
			return HttpResponseRedirect('/')
		else:
			print form.errors
	else:
		form = RequestForm()
	return render(request, 'Calendar/createreq.html', {'form' : form})

def returnApps(list):
	"""
	Retourne la liste des applications a partir d'une liste de QuerySet.
	"""
	applist = []
	for l in list:
		app = Application.objects.filter(id=l)
		applist.append(app[0].get_appname())
	return applist

def editRequest(request, title):
	"""
	La fonction editRequest cree un formulaire a partir de l'instance de Request que l'on veut editer.
	Lorsque les modifications sont faites, la demande est sauvegardee.
	"""
	tomodif = Request.objects.get(id=title)
	if request.method == 'POST':
		form = RequestFormEdit(request.POST, instance=tomodif)	
		if form.has_changed:
			changes = []
			for changed in form.changed_data:
				if changed == 'apps':
					modif = changed + " avant " + tomodif.get_apps() + " apres " + ", ".join(returnApps(form[changed].value()))
					changes.append(modif)
					change = History.objects.create(request = tomodif, fieldmodified=changed, valuebefore=tomodif.get_apps(), valueafter = ", ".join(returnApps(form[changed].value())))
				elif changed == 'start' or changed == 'end' or changed == 'daterefresh':
					modif = changed + " avant " + str(getattr(tomodif, changed)) + " apres " + str(form[changed].value())
                                        changes.append(modif)
                                        change = History.objects.create(request = tomodif, fieldmodified=changed, valuebefore=getattr(tomodif, changed), valueafter = datetime.datetime.strptime(form[changed].value(), "%m/%d/%Y").date())
				else:
					modif = changed + " avant " + str(getattr(tomodif, changed)) + " apres " + str(form[changed].value())
                                        changes.append(modif)

Calendar/templates/Calendar/assign.html
{% extends 'Calendar/base.html' %}
{% block body %}

	<div align="center">
		<form action="/assign/{{ form.initial.id }}" method="POST">
		{% csrf_token %}
			{% for field in form %}
			    	<div class="fieldWrapper">
	        			<p class="error">{{ field.errors.as_text }}</p>
	        			{{ field.label_tag }} {{ field }}
	    			</div>
			{% endfor %}
		<input type="submit" value="Assigner" />
		</form>
	</div>

	<div align="center">
		<form action="/delete/{{ form.initial.id }}" method="GET">
			<input type="submit" value="Supprimer">
		</form>
	</div>

{% endblock %}

Calendar/templates/Calendar/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<link href="{{STATIC_URL}}css/style.css" rel="stylesheet">
		<link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
		<script src="//code.jquery.com/jquery.js"></script>
		<script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
		<script src="{{STATIC_URL}}js/bootstrap.min.js"></script>
	<script>
		$(document).ready(function () {
			if ($("#id_batchs").prop('checked')){

                                $( ".batchType" ).show();
                        }
                        else{
                                $( ".batchType" ).hide();
                        }
               		if ($("#id_refresh").prop('checked')){
                                $( ".daterefresh" ).show();
                        }
                        else{
                                $( ".daterefresh" ).hide();
                        }
                        $( ".hist" ).hide();
                        $( "#editrequest" ).fadeToggle("slow");


		});
		$(function() {
			$( "#dateFrom" ).datepicker();
			$( "#dateTo" ).datepicker();
			$( "#dateRefresh" ).datepicker();
			//$( "#datefromselect" ).datepicker({ dateFormat: 'yy-mm-dd' });
			$( "#datefromselect" ).datepicker();
			//$( "#datetoselect" ).datepicker({ dateFormat: 'yy-mm-dd' });
			$( "#datetoselect" ).datepicker();
			$( "#id_refresh" ).click(function() {
				if ($("#id_refresh").prop('checked')){
					$( ".daterefresh" ).fadeToggle("slow");
				}
				else{
					$( ".daterefresh" ).fadeToggle("slow");
				}
			});
			$( "#id_batchs" ).click(function() {
				if ($("#id_batchs").prop('checked')){
					$( ".batchType" ).fadeToggle("slow");
				}
				else{
					$( ".batchType" ).fadeToggle("slow");
				}
			});
			$( "#showhistory" ).click(function() {
				$( ".hist" ).fadeToggle("slow");
					var pos=$("#hist").offset().top;
					if( $( ".hist" ).attr("name")) {
						$('html, body').animate({scrollTop:pos}, 'slow');
						$( "#showhistory" ).val("Cacher l'historique");
						$( ".hist" ).removeAttr("name");		
					}
					else{
						$('html, body').animate({scrollTop:0}, 'slow');
						$( "#showhistory" ).val("Historique de la demande");
						$( ".hist" ).attr("name", "cache");
					}
			});
			$( "#printbtn").click( function() {
				window.print();
			});

		});
	</script>
	<div width="100%" style="text-align: center; position: relative;">
		<p><h1>Environnement Management</h1></p>
	</div>


	</head>


	<body>
	<div width="100%" class="nav" style="position: relative; top: 0px">
		<ul>
			<li><a href="/create/" class="links">Nouvelle demande</a></li>
			<li><a href="/" class="links">liste des demandes</a></li>
			<li><a href="/login/" class="links">Connexion Admin</a></li>
			{% if user.is_authenticated %}
			<li><a href="/admin/" class="links">Administration</a></li>
			<li><a href="/logout/" class="links">Deconnexion</a></li>
			{% endif %}
		</ul>
	</div>
	<div>
		{% block body %} {% endblock %}
	</div>

	</body>
</html>

Calendar/templates/Calendar/createreq.html
{% extends 'Calendar/base.html' %}
{% block body %}
	<div align="center">
	<form action="/create/" method="POST">
	{% csrf_token %}
		{% for field in form %}
		    	<div class={{field.name}}>
        			<p class="error">{{ field.errors.as_text }}</p>
        			{{ field.label_tag }} <br>{{ field }}
				
			</div>
		{% endfor %}
	</div>
	<div align="center">
	<input type="submit" class="btn btn-primary" value="Creer" />
	</div>
{% endblock %}

Calendar/templates/Calendar/edit.html
{% extends 'Calendar/base.html' %}
{% block body %}

	<div align="center">
		<form action="/edit/{{ form.initial.id }}" method="POST">
		{% csrf_token %}
			{% for field in form %}
			    	<div class={{field.name}}>
	        			<p class="error">{{ field.errors.as_text }}</p>
	        			{{ field.label_tag }}<br> {{ field }}
	    			</div>
			{% endfor %}
		<input type="submit" value="Sauvegarder" />
		</form>
	</div>

	<div align="center">
		<form action="/delete/{{ form.initial.id }}" method="GET">
			<input type="submit" value="Supprimer">
		</form>
	</div>

{% endblock %}

Calendar/templates/Calendar/index.html
{% extends 'Calendar/base.html' %}
{% load Calendar_extras %
{% block body %}
<div style="position: relative;top: 0px; left; 0px;width: 100%">
<form class="navbar-search pull-right" action="/makeView/" method="get">
	<div style="position: absolute; top 0px; left: 75px;">Debut: {{form.datefrom}}</div>
	<div style="position: absolute; top 0px; left: 300px;">Fin: {{form.dateto}}</div>
	<div style="position: absolute; top 0px; left: 500px;">Resolution de l'ecran: {{form.size}}</div>
        <input style="position: absolute; top 0px; left: 800px; width: 80px;" type="submit" value="voir">
</form>
</div>
<div align="center" style="position: relative; top: 50px; display: block;">
<table width="85%">
	<thead>
		<tr class="tablehead">
		<th width="10%">Intitule</th>
		<th width="10%">Reference</th>
		<th width="10%">Debut</th>
		<th width="10%">Fin</th>
		<th width="10%">Applications</th>
		<th width="10%">Version</th>
		<th width="10%">Env</th>
		<th width="10%">Demandeur</th>
		{% if user.is_authenticated %}
		<th width="10%">Assign</th>
		{% endif %}
		</tr>
	</thead>
	<tbody>
		{% if list_req %}
		{% for req in list_req %}
			<tr class="linkable">
			<a href="/edit/{{ req.id }}">
			<td>{{ req.title }}</td>
			<td>{{ req.reference }}</td>
			<td>{{ req.start }}</td>
			<td>{{ req.end }}</td>
			<td>{{ req.get_apps }}</td>
			<td>{{ req.version }}</td>
			<td>{{ req.env }}</td>
			<td>{{ req.trigram }}</td>
			</a>
			{% if user.is_authenticated %}
			<a href="/assign/{{ req.id }}">
			{% if not req.env %}
			<td>Assign</td>
			{% endif %}
			{% if req.env %}
			<td>Re-Assign</td>
			{% endif %}
			</a>
			{% endif %}
			</tr>
		{% endfor %}
		{% endif %}
	</tbody>
</table>
</div>


{% endblock %}	

Calendar/templates/Calendar/login.html
<html>
<head> <title>connexion administration</title> 
<link href="{{STATIC_URL}}css/bootstrap.css" rel="stylesheet">

</head>
<body>
<div align="center">
<h1>Connexion</h1>
{% if form.errors %}
<p>Your username and password didn't match!
Please try again!</p>
{% endif %}
<form method="post" action="." class="form-horizontal">
{% csrf_token %}
<p><label for="id_username">Login:</label>{{ form.username }}</p>
<p><label for="id_password">Mot de passe:</label>{{ form.password }}</p>
<input type="hidden" name="next" value="{{ next }}" />
<input type="submit" value="Connexion" class="btn btn-large"/>
</form>
</div>
</body>
</html>

Calendar/templates/Calendar/request_list.html
<form action="/save/" method="post">
{% block body %}
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="create"/>
</form>

{% endblock %}

Calendar/templates/Calendar/view.html
{% extends 'Calendar/base.html' %}
{% load Calendar_extras %}
{% block body %}
<!--<form class="navbar-search pull-right" action="/makeView/" method="get">
		<input type="text" name="datefrom" class="input-medium search-query">
		<input type="text" name="dateto" class="input-medium search-query">
		<input type="submit" value="voir">
</form>-->
<div style="position: relative;top: 0px; left; 0px;width: 100%">
<form class="navbar-search pull-right" action="/makeView/" method="get">
	<div style="position: absolute; left: 110px;" class="error">{{form.datefrom.errors.as_text }}</div>
        <div style="position: absolute; top: {%if form.datefrom.errors or form.dateto.errors %} 30px {%else%} 0px {%endif%}; left: 75px;">Debut: {{form.datefrom}}</div>
	<div style="position: absolute; left: 320px;" class="error">{{form.dateto.errors.as_text }}</div>
        <div style="position: absolute; top: {%if form.datefrom.errors or form.dateto.errors %} 30px {%else%} 0px {%endif%}; left: 300px;">Fin: {{form.dateto}}</div>
	<div style="position: absolute; top: {%if form.datefrom.errors or form.dateto.errors %} 30px {%else%} 0px {%endif%}; left: 500px;">{{ form.size}}</div>
        <input style="position: absolute; top: {%if form.datefrom.errors or form.dateto.errors %} 30px {%else%} 0px {%endif%}; left: 700px; width: 80px;" type="submit" value="voir">
</form>
</div>
{% if reqs %}
	{% if infos %}
<div width="100%" style="position: relative; top:50px">
	<div style="position: absolute; top: 0px; left:10px; width: {{infos.2}}px; display: block;"></div>
		<div style="position: absolute; left: 0px; top: 0px; width:76px; display: block;"></div>
		{% for m in month %}<div style="position: absolute; left: {{m.2}}px; top: 0px; width: {{m.1|multiply:infos.1}}px; display: block; border: 1px solid black; text-align: center;">{{m.0}} </div> {% endfor %}
	{% for day in dates %}
		<div style="height: 800px; background-color: white; position: absolute; display: block; top: 20px; padding-top: 3px;left: {{ forloop.counter0|multiply:infos.1|add:76}}px; width: {{infos.1}}px; overflow: auto; border-left: 1px dashed black; {% if forloop.last %} border-right: 1px dashed black; {% endif %} font-size: 12px; text-align: center;">{{day|displaydaydate}}</div>
	{% endfor %}
	{% for r in reqs %}
</div>
	<div width="100%" style="position: relative; top: 70px">
		<div style="position: absolute; top: {% ifchanged r.name %}{{forloop.counter0|multiply:150|add:20}}px{% endifchanged %}; width: {{infos.2}}px; display: block; left: 10px; border: 2px solid black; border-radius: 5px 10px 0 5px; background-color:{% cycle '#54C571' '#F75D59' '#C2DFFF' %}; line-height: 150px; vertical-align: middle; height:150px; text-align: center;">{{r.name}}
		</div>
		<div style="position: absolute; top: {% ifchanged r.name %}{{forloop.counter0|multiply:150|add:20}}px{% endifchanged %}; width: {{infos.3}}px; display: block; left: 75px; border: 2px solid black; border-radius: 5px 10px 0 5px; background-color:{% cycle '#54C571' '#F75D59' '#C2DFFF' %}; height:150px">{% for re in r.reqlist %} <a href="/viewrequest/{{re.0.id}}"><div style="position: absolute; background-color: blue; width: {{re.1.size}}px; left: {{re.1.offset}}px; height:30px; top:{{re.1.yoffset}}px; line-height: 30px; vertical-align: middle; text-align:center; border: 1px dashed white">{{re.0.title}} : {{re.0|appslist|lower}}</div></a>{% endfor %}</div>
		<br>
	</div>
	{% endfor %}
	{% endif %}
{% endif %}

{% endblock %}